# Generated by Django 4.2.3 on 2023-08-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyer_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='selled',
            field=models.BooleanField(default=False),
        ),
    ]
